cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: null
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: null
    you:
      email: sksj0111@naver.com
      name: you
      password: $2b$12$PEb5Qpx0FYzR2UpTWJfvqeWoWCimPv2LUIR/CW5cFE8nPeLxfl0pW
    youhyeonseok:
      email: sksj0111@naver.com
      name: youhyeonseok
      password: $2b$12$IBTmbPCTId4WRkYEb8Ede.whGHTYLixNbdM3wq.rKHs21y5voExBG
preauthorized:
  emails:
  - melsby@gmail.com
